# Generated by Django 4.2.3 on 2026-09-19 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الجوال')),
                ('role', models.CharField(choices=[('manager', 'مدير'), ('cashier', 'كاشير'), ('chef', 'طاهٍ'), ('driver', 'سائق'), ('call_center', 'خدمة عملاء'), ('waiter', 'مباشر')], max_length=50, verbose_name='المسمى الوظيفي')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('vacation', 'في إجازة'), ('inactive', 'غير نشط')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('category', models.CharField(max_length=100, verbose_name='الفئة')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='سعر البيع')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='التكلفة')),
                ('emoji', models.CharField(blank=True, default='', max_length=20, verbose_name='أيقونة')),
                ('available', models.BooleanField(default=True, verbose_name='متوفر')),
            ],
            options={
                'verbose_name': 'صنف منيو',
                'verbose_name_plural': 'قائمة الطعام',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('order_type', models.CharField(choices=[('dine_in', 'محلي'), ('takeaway', 'سفري'), ('delivery', 'توصيل')], default='dine_in', max_length=20, verbose_name='نوع الطلب')),
                ('channel', models.CharField(choices=[('cashier', 'الكاشير'), ('call_center', 'الكول سنتر')], default='cashier', max_length=20, verbose_name='القناة')),
                ('customer_name', models.CharField(default='عميل نقدي', max_length=255, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='هاتف العميل')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان التوصيل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز للتسليم'), ('out_for_delivery', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=30, verbose_name='الحالة')),
                ('pay_method', models.CharField(choices=[('cash', 'نقداً'), ('card', 'بطاقة'), ('wallet', 'محفظة رقمية')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('paid', models.BooleanField(default=True, verbose_name='تم الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع الفرعي')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='رسوم التوصيل')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإجمالي')),
                ('cashier', models.CharField(blank=True, default='', max_length=255, verbose_name='الكاشير')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الطلب')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer', verbose_name='العميل')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='core.employee', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='سعر الوحدة')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.menuitem', verbose_name='صنف المنيو')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('unit', models.CharField(default='كجم', max_length=50, verbose_name='الوحدة')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الكمية المتوفرة')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='حد الأمان الأدنى')),
                ('supplier', models.CharField(blank=True, default='', max_length=255, verbose_name='المورد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'عنصر مخزون',
                'verbose_name_plural': 'المخزون',
                'ordering': ['id'],
            },
        ),
    ]
