# Generated by Django 4.2.3 on 2026-09-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالك / إدارة عامة'), ('branch_manager', 'مدير فرع'), ('cashier', 'كاشير'), ('chef', 'طاهٍ / مطبخ'), ('driver', 'سائق توصيل'), ('call_center', 'خدمة عملاء')], default='branch_manager', max_length=30, verbose_name='الدور والصلاحية')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='core.branch', verbose_name='الفرع المعين')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='BranchMenuAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر في هذا الفرع')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_menus', to='core.branch', verbose_name='الفرع')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='core.menuitem', verbose_name='صنف المنيو')),
            ],
            options={
                'verbose_name': 'توفر الصنف بالفرع',
                'verbose_name_plural': 'توفر الأصناف بالفروع',
                'unique_together': {('branch', 'menu_item')},
            },
        ),
    ]
