# Generated by Django 4.2.3 on 2026-09-19 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userprofile_branchmenuavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المطعم / المنشأة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='المعرف اللاتيني (Slug)')),
                ('logo_emoji', models.CharField(blank=True, default='🍽️', max_length=20, verbose_name='شعار / أيقونة')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='المقر الرئيسي')),
                ('plan', models.CharField(choices=[('trial', 'تجريبي'), ('standard', 'أساسي'), ('premium', 'متقدم'), ('enterprise', 'شركات')], default='standard', max_length=30, verbose_name='خطة الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مستأجر / منشأة',
                'verbose_name_plural': 'المستأجرون (المنشآت والمطاعم)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, help_text='مثال: 101 أو EMP-101', max_length=30, null=True, verbose_name='كود الموظف للدخول السريع'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pin_code',
            field=models.CharField(blank=True, help_text='رمز دخول سريع من 4 أرقام', max_length=128, null=True, verbose_name='رمز PIN المشفر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم المربوط'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='مسؤول النظام والمنصة بالكامل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'مسؤول المنصة العامة (SaaS Admin)'), ('owner', 'مالك / إدارة عامة للمطعم'), ('branch_manager', 'مدير فرع'), ('cashier', 'كاشير'), ('chef', 'طاهٍ / مطبخ'), ('driver', 'سائق توصيل'), ('call_center', 'خدمة عملاء'), ('waiter', 'مباشر')], default='branch_manager', max_length=30, verbose_name='الدور والصلاحية'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.tenant', verbose_name='المستأجر / المنشأة'),
        ),
    ]
