# Generated by Django 4.2.3 on 2026-09-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_employee_employee_code_employee_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='delivery_polygon',
            field=models.JSONField(blank=True, default=list, verbose_name='مضلع التغطية على الخريطة'),
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نصف قطر التغطية (كم)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنطقة / الكومبوند')),
                ('area_type', models.CharField(choices=[('compound', 'كومبوند / مجمع سكني'), ('district', 'حي سكني'), ('zone', 'منطقة / قطاع'), ('commercial', 'منطقة تجارية / مول')], default='compound', max_length=30, verbose_name='نوع المنطقة')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=8.0, max_digits=8, verbose_name='رسوم التوصيل')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=35, verbose_name='وقت التوصيل التقديري (دقيقة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة للتوصيل')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات / بوابات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='core.branch', verbose_name='الفرع التابع له')),
            ],
            options={
                'verbose_name': 'منطقة تغطية وكومبوند',
                'verbose_name_plural': 'المناطق والكومبوندات المغطاة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.deliveryarea', verbose_name='منطقة التوصيل / الكومبوند'),
        ),
    ]
