# Generated by Django 4.2.3 on 2026-09-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_delivery_polygon_branch_delivery_radius_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المسمى الوظيفي')),
                ('scope', models.CharField(choices=[('hq', 'إدارة عامة (HQ)'), ('branch', 'تشغيل فرع'), ('both', 'شامل (إدارة وفروع)')], default='branch', max_length=20, verbose_name='نطاق العمل')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف المهام')),
                ('is_system', models.BooleanField(default=False, verbose_name='مسمى أساسي للنظام')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='مصفوفة الصلاحيات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='core.tenant', verbose_name='المطعم / المنشأة')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي وصلاحيات',
                'verbose_name_plural': 'المسميات الوظيفية والصلاحيات',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.jobrole', verbose_name='المسمى الوظيفي المخصص'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.jobrole', verbose_name='المسمى الوظيفي المخصص'),
        ),
    ]
