# Generated by Django 4.2.3 on 2026-09-20 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobrole_employee_job_role_userprofile_job_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('code', models.SlugField(unique=True, verbose_name='كود الباقة')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف الباقة')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='السعر الشهري (ر.س)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='السعر السنوي (ر.س)')),
                ('max_branches', models.IntegerField(default=1, verbose_name='الحد الأقصى للفروع (0 لغير محدود)')),
                ('max_employees', models.IntegerField(default=5, verbose_name='الحد الأقصى للموظفين (0 لغير محدود)')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='الميزات المفعلة في الباقة')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='أيام التجربة المجانية')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للاشتراك')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الباقة الأكثر طلباً')),
                ('ordering', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'باقة اشتراك SaaS',
                'verbose_name_plural': 'باقات اشتراك المنصة',
                'ordering': ['ordering', 'price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي'), ('trial', 'تجريبي')], default='monthly', max_length=20, verbose_name='دورة الفوترة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ بدء الاشتراك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'فترة تجريبية'), ('active', 'نشط'), ('expired', 'منتهي'), ('grace_period', 'فترة سماح')], default='active', max_length=20, verbose_name='حالة الاشتراك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.subscriptionplan', verbose_name='باقة الاشتراك'),
        ),
    ]
