# Generated by Django 4.2.3 on 2026-09-20 15:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_upgraderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
            ],
            options={
                'verbose_name': 'مالك منشأة / مطعم',
                'verbose_name_plural': 'قائمة الملاك (Restaurant Owners)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'مشترك / اشتراك منشأة',
                'verbose_name_plural': 'قائمة المشتركين (Subscribers)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tenant',),
        ),
        migrations.CreateModel(
            name='TenantApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='مفتاح كول سنتر الذكاء الاصطناعي', max_length=120, verbose_name='اسم المفتاح / البوت')),
                ('key', models.CharField(db_index=True, default=core.models.generate_api_key, max_length=80, unique=True, verbose_name='مفتاح الدخول (Access Key)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('total_orders_placed', models.PositiveIntegerField(default=0, verbose_name='الطلبات المنفذة عبره')),
                ('assigned_branch', models.ForeignKey(blank=True, help_text='اتركه فارغاً للسماح للبوت بخدمة كافة فروع المنشأة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='core.branch', verbose_name='الفرع المخصص (اختياري)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.tenant', verbose_name='المنشأة / المطعم')),
            ],
            options={
                'verbose_name': 'مفتاح ذكاء اصطناعي (API Key)',
                'verbose_name_plural': 'مفاتيح الذكاء الاصطناعي (AI Access Keys)',
                'ordering': ['-created_at'],
            },
        ),
    ]
