# Generated by Django 6.1.1 on 2026-09-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurantowner_tenantsubscription_tenantapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='voice_client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='معرف الكول سنتر (Client ID)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='voice_is_active',
            field=models.BooleanField(default=False, verbose_name='تفعيل الكول سنتر الصوتي'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='voice_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='كلمة مرور السنترال (Voice PBX Password)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='voice_username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم مستخدم السنترال (Voice PBX Username)'),
        ),
    ]
