# Generated by Django 6.1.1 on 2026-10-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jobrole_options_jobrole_group_jobrole_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='permissions',
        ),
    ]
