# Generated by Django 6.1.1 on 2026-10-03 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_jobrole_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='نوع العملية')),
                ('target_model', models.CharField(blank=True, max_length=64, verbose_name='النموذج المتأثر')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='معرف السجل')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant', verbose_name='المنشأة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ')),
            ],
            options={
                'verbose_name': 'سجل التدقيق الأمني',
                'verbose_name_plural': 'سجلات التدقيق الأمني',
                'ordering': ['-created_at'],
            },
        ),
    ]
