from django.urls import path
from . import views

urlpatterns = [
    path("", views.landing_view, name="landing"),
    path("home/", views.landing_view, name="home"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("subscription/", views.owner_subscription_view, name="owner_subscription"),
    path("hq/orders/", views.hq_orders_view, name="hq_orders"),
    path("platform/", views.platform_dashboard_view, name="platform_dashboard"),
    path("platform/switch-tenant/<int:tenant_id>/", views.switch_tenant_view, name="switch_tenant"),
    path("branch/", views.branch_dashboard_view, name="branch_dashboard"),
    path("branch/switch/<str:branch_id>/", views.switch_branch_view, name="switch_branch"),
    path("kitchen/", views.kitchen_view, name="kitchen"),
    path("api/kitchen/stream/", views.kitchen_stream_view, name="kitchen_stream"),
    path("api/kitchen/live/", views.kitchen_live_view, name="kitchen_live"),
    path("branch/orders/", views.branch_orders_view, name="branch_orders"),
    path("branch/menu/", views.branch_menu_view, name="branch_menu"),

    path("pos/", views.pos_view, name="pos"),
    path("call-center/", views.call_center_view, name="call_center"),
    path("delivery/", views.delivery_view, name="delivery"),
    path("inventory/", views.inventory_view, name="inventory"),
    path("branches/", views.branches_view, name="branches"),
    path("employees/", views.employees_view, name="employees"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("set-language/<str:lang_code>/", views.set_language_view, name="set_language"),
    
    path("orders/<int:order_id>/", views.order_detail_view, name="order_detail"),
    path("orders/<int:order_id>/edit/", views.order_edit_view, name="order_edit"),

    # Internal JSON APIs
    path("api/tenants/create/", views.api_create_tenant, name="api_create_tenant"),
    path("api/orders/", views.api_create_order, name="api_create_order"),
    path("api/orders/<int:order_id>/", views.api_update_order, name="api_update_order"),
    path("api/orders/<int:order_id>/cancel/", views.api_cancel_order, name="api_cancel_order"),
    path("api/orders/<int:order_id>/delete/", views.api_delete_order, name="api_delete_order"),
    path("api/branch-menu/toggle/<int:item_id>/", views.api_toggle_branch_menu, name="api_toggle_branch_menu"),
    path("api/customers/search/", views.api_search_customers, name="api_search_customers"),
    path("api/menu/toggle/<int:item_id>/", views.api_toggle_menu_item, name="api_toggle_menu_item"),
    path("api/menu/create/", views.api_create_menu_item, name="api_create_menu_item"),
    path("api/menu/<int:item_id>/", views.api_update_menu_item, name="api_update_menu_item"),
    path("api/menu/<int:item_id>/delete/", views.api_delete_menu_item, name="api_delete_menu_item"),
    path("api/inventory/adjust/<int:item_id>/", views.api_adjust_inventory, name="api_adjust_inventory"),
    path("api/inventory/create/", views.api_create_inventory, name="api_create_inventory"),
    path("api/inventory/delete/<int:item_id>/", views.api_delete_inventory, name="api_delete_inventory"),
    path("api/branches/create/", views.api_create_branch, name="api_create_branch"),
    path("api/branches/toggle/<int:branch_id>/", views.api_toggle_branch, name="api_toggle_branch"),
    path("api/branches/<int:branch_id>/areas/", views.api_branch_delivery_areas, name="api_branch_delivery_areas"),
    path("api/employees/create/", views.api_create_employee, name="api_create_employee"),
    path("api/employees/<int:emp_id>/", views.api_update_employee, name="api_update_employee_short"),
    path("api/employees/update/<int:emp_id>/", views.api_update_employee, name="api_update_employee"),
    path("api/employees/<int:emp_id>/delete/", views.api_delete_employee, name="api_delete_employee"),
    path("api/employees/<int:emp_id>/toggle-status/", views.api_toggle_employee_status, name="api_toggle_employee_status"),
    path("api/employees/<int:emp_id>/detail/", views.api_employee_detail, name="api_employee_detail"),
    path("api/employees/export-csv/", views.api_export_employees_csv, name="api_export_employees_csv"),
    path("api/job-roles/", views.api_job_roles, name="api_job_roles"),
    path("api/job-roles/<int:role_id>/", views.api_job_role_detail, name="api_job_role_detail"),
    path("api/platform/plans/", views.api_subscription_plans, name="api_subscription_plans"),
    path("api/platform/plans/<int:plan_id>/", views.api_subscription_plan_detail, name="api_subscription_plan_detail"),
    path("api/platform/tenants/<int:tenant_id>/subscription/", views.api_update_tenant_subscription, name="api_update_tenant_subscription"),
    path("api/subscription/request-upgrade/", views.api_request_upgrade, name="api_request_upgrade"),
    path("api/platform/upgrade-requests/<int:req_id>/review/", views.api_review_upgrade_request, name="api_review_upgrade_request"),
    path("api/api-keys/create/", views.api_create_api_key, name="api_create_api_key"),
    path("api/api-keys/<int:key_id>/toggle/", views.api_toggle_api_key, name="api_toggle_api_key"),
    path("api/api-keys/<int:key_id>/delete/", views.api_delete_api_key, name="api_delete_api_key"),

    # AI Call Center Management
    path("ai-callcenter/", views.ai_callcenter_management_view, name="ai_callcenter_management"),
    path("api/ai-callcenter/profile/", views.api_ai_callcenter_update_profile, name="api_ai_callcenter_update_profile"),
    path("api/ai-callcenter/profile/<int:profile_id>/", views.api_ai_callcenter_update_profile, name="api_ai_callcenter_update_profile_id"),
    path("api/ai-callcenter/profiles/create/", views.api_ai_callcenter_create_profile, name="api_ai_callcenter_create_profile"),
    path("api/ai-callcenter/profiles/<int:profile_id>/activate/", views.api_ai_callcenter_activate_profile, name="api_ai_callcenter_activate_profile"),
    path("api/ai-callcenter/profiles/<int:profile_id>/delete/", views.api_ai_callcenter_delete_profile, name="api_ai_callcenter_delete_profile"),
    path("api/ai-callcenter/hours/", views.api_ai_callcenter_update_hours, name="api_ai_callcenter_update_hours"),
    path("api/ai-callcenter/docs/add/", views.api_ai_callcenter_add_doc, name="api_ai_callcenter_add_doc"),
    path("api/ai-callcenter/docs/<int:doc_id>/delete/", views.api_ai_callcenter_delete_doc, name="api_ai_callcenter_delete_doc"),
    path("api/ai-callcenter/employees/add/", views.api_ai_callcenter_add_employee, name="api_ai_callcenter_add_employee"),
    path("api/ai-callcenter/employees/<int:emp_id>/delete/", views.api_ai_callcenter_delete_employee, name="api_ai_callcenter_delete_employee"),
    path("api/ai-callcenter/queues/save/", views.api_ai_callcenter_save_queue, name="api_ai_callcenter_save_queue"),
    path("api/ai-callcenter/queues/<int:queue_id>/delete/", views.api_ai_callcenter_delete_queue, name="api_ai_callcenter_delete_queue"),
    path("api/ai-callcenter/queues/<int:queue_id>/members/add/", views.api_ai_callcenter_add_queue_member, name="api_ai_callcenter_add_queue_member"),
    path("api/ai-callcenter/mcp/sync/", views.api_ai_callcenter_sync_mcp, name="api_ai_callcenter_sync_mcp"),
    path("api/ai-callcenter/mcp/update-url/", views.api_ai_callcenter_update_mcp_url, name="api_ai_callcenter_update_mcp_url"),
    path("api/ai-callcenter/mcp/test-tool/", views.api_ai_callcenter_test_mcp_tool, name="api_ai_callcenter_test_mcp_tool"),
    path("api/ai-callcenter/sync-live-context/", views.api_ai_callcenter_sync_live_context, name="api_ai_callcenter_sync_live_context"),
    path("api/ai-callcenter/get-live-context/", views.api_ai_callcenter_get_live_context, name="api_ai_callcenter_get_live_context"),
    path("api/audit-logs/", views.api_audit_logs, name="api_audit_logs"),
]

